// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/stubborn-gaga-0805/prepare2go/internal/server"
)

// Injectors from wire.go:

func initServer(contextContext context.Context) (*server.Server, func(), error) {
	serverServer := server.NewHttpServer()
	return serverServer, func() {
	}, nil
}

func initWebSocket(contextContext context.Context) (*server.Websocket, func(), error) {
	websocket := server.NewWebsocketServer()
	return websocket, func() {
	}, nil
}
